### ISSUE TITLE
Source Constrain should be part of the node it constraints and not of the generator system

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#177]
Possibly a huge change with a lot of side effects. Requires developer detail information if it is possible, makes sense and what everything could be affected by this.

**Comment by UrsZeidler** [comment]
Your are right, this would be the natural way of modeling these constrains.  
But after thinking over this a while I find it more convenient to bind the constrains to the generator system as it is the responsibility of  generator system keeping the information about the rules, otherwise parts of the rules would be spread around the whole resource set.

These design decision makes it possible to simple 'house rule' these rule aspects.


ps. To be honest, 'separation of concerns' is an important rule in OOP I could not break it.
